# Generated by Django 3.1.6 on 2021-05-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance',
            new_name='Health_Insurance',
        ),
    ]
