# Generated by Django 3.1.6 on 2021-05-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0004_auto_20210517_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('health_data', models.ManyToManyField(to='global.Health_Insurance')),
                ('life_data', models.ManyToManyField(to='global.Life_Insurance')),
            ],
        ),
    ]
