# Generated by Django 3.1.6 on 2021-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0007_auto_20210518_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_own',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
