# Generated by Django 3.1.6 on 2021-05-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0009_auto_20210518_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
