# Generated by Django 3.1.6 on 2021-05-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0010_auto_20210519_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_own',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_own',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user_own',
            name='user_name',
            field=models.CharField(max_length=150),
        ),
    ]
