# Generated by Django 3.1.6 on 2021-05-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0011_auto_20210519_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_own',
            name='details',
        ),
        migrations.AddField(
            model_name='details',
            name='newid',
            field=models.IntegerField(null=True),
        ),
    ]
