# Generated by Django 3.2.3 on 2021-05-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0012_auto_20210519_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.CharField(max_length=100),
        ),
    ]
