# Generated by Django 3.2.3 on 2021-05-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0013_alter_details_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='start_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
